#! /bin/sh
# This script is only for Jenkins to run just before the build.
# It's all platform-specific.

cat <<EOF > testing.properties
ZooKeeperQuorum = hdhbase01.int.softartisans.com
ZooKeeperClientPort = 2181
ExchangeURI = https://devexch01.int.tartarus.com/ews/exchange.asmx
LdapDomain = int.tartarus.com
LdapConfigEntry = Timberwolf
# Exchange Users
ExchangeUser1 = jenkins1
ExchangeUser2 = jenkins2
ExchangeUser3 = jenkins3
ExchangeSender = jenkinsSender
ExchangeIgnoredUser = jenkinsIgnored
EOF

# jclouseau is the user who can impersonate everyone else.
echo pass@word1 | kinit jenkinsSender@INT.TARTARUS.COM
