#! /bin/sh
# This script is only for Jenkins to run just before the build.
# It's all platform-specific.

echo "ZooKeeperQuorum = hdhbase01.int.softartisans.com\nZooKeeperClientPort = 2181" > testing.properties

# jclouseau is the user who can impersonate everyone else.
echo pass@word1 | kinit jclouseau@INT.TARTARUS.COM
